//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SY.HL7.Parser.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SY.HL7.Parser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SII_Z12 xmlns=&quot;urn:hl7-org:v2xml&quot;&gt;  
        ///  &lt;MSH&gt; 
        ///    &lt;MSH.1&gt;{{MSH_1}}&lt;/MSH.1&gt;  
        ///    &lt;MSH.2&gt;{{MSH_2}}&lt;/MSH.2&gt;  
        ///    &lt;MSH.3&gt; 
        ///      &lt;HD.1&gt;{{MSH_3_HD_1}}&lt;/HD.1&gt; 
        ///    &lt;/MSH.3&gt;  
        ///    &lt;MSH.4&gt; 
        ///      &lt;HD.1&gt;{{MSH_4_HD_1}}&lt;/HD.1&gt; 
        ///    &lt;/MSH.4&gt;  
        ///    &lt;MSH.7&gt;{{MSH_7}}&lt;/MSH.7&gt;  
        ///    &lt;MSH.9&gt; 
        ///      &lt;MSG.1&gt;SII&lt;/MSG.1&gt;  
        ///      &lt;MSG.2&gt;Z12&lt;/MSG.2&gt;  
        ///      &lt;MSG.3&gt;SII_Z12&lt;/MSG.3&gt; 
        ///    &lt;/MSH.9&gt;  
        ///    &lt;MSH.10&gt;{{MSH_10}}&lt;/MSH.10&gt;  
        ///    &lt;MSH.11&gt; 
        ///      &lt;PT.1&gt;P&lt;/PT.1&gt; 
        ///    &lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SII_Z12_XML_TEMPLATE {
            get {
                return ResourceManager.GetString("SII_Z12_XML_TEMPLATE", resourceCulture);
            }
        }
    }
}
