//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7Lib.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HL7Lib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Church 
        ///High 
        ///Chestnut 
        ///Elm 
        ///B 
        ///2nd 
        ///Walnut 
        ///Main North
        ///Maple 
        ///Maple 
        ///Center 
        ///Main South
        ///Washington 
        ///Pine 
        ///River 
        ///South 
        ///Union 
        ///Water 
        ///Main West
        ///Main East
        ///Park 
        ///School 
        ///Spring 
        ///Oak 
        ///Prospect 
        ///Market 
        ///North 
        ///3rd 
        ///Front 
        ///Park 
        ///Washington 
        ///Highland 
        ///Cedar 
        ///Central 
        ///Spruce 
        ///State 
        ///West 
        ///Franklin 
        ///Ridge 
        ///4th 
        ///Church 
        ///Lincoln 
        ///Pleasant 
        ///Bridge 
        ///Cherry 
        ///East 
        ///Locust 
        ///Winding  
        ///Route 1
        ///1st 
        ///5th 
        ///Cherry  
        ///Mill 
        ///Park Place
        ///Route 30
        ///2nd 
        ///Academy 
        ///Adams 
        ///Beech         /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Address_Names {
            get {
                return ResourceManager.GetString("Address_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jacob
        ///Ethan
        ///Michael
        ///Alexander
        ///William
        ///Joshua
        ///Daniel
        ///Jayden
        ///Noah
        ///Anthony
        ///Christopher
        ///Aiden
        ///Matthew
        ///David
        ///Andrew
        ///Joseph
        ///Logan
        ///James
        ///Ryan
        ///Benjamin
        ///Elijah
        ///Gabriel
        ///Christian
        ///Nathan
        ///Jackson
        ///John
        ///Samuel
        ///Tyler
        ///Dylan
        ///Jonathan
        ///Caleb
        ///Nicholas
        ///Gavin
        ///Mason
        ///Evan
        ///Landon
        ///Angel
        ///Brandon
        ///Lucas
        ///Isaac
        ///Isaiah
        ///Jack
        ///Jose
        ///Kevin
        ///Jordan
        ///Justin
        ///Brayden
        ///Luke
        ///Liam
        ///Carter
        ///Owen
        ///Connor
        ///Zachary
        ///Aaron
        ///Robert
        ///Hunter
        ///Thomas
        ///Adrian
        ///Cameron
        ///Wyatt
        ///Chase
        ///Julian
        ///Austin
        ///Charles
        ///Jeremiah [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Boy_Names {
            get {
                return ResourceManager.GetString("Boy_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Isabella
        ///Emma
        ///Olivia
        ///Sophia
        ///Ava
        ///Emily
        ///Madison
        ///Abigail
        ///Chloe
        ///Mia
        ///Elizabeth
        ///Addison
        ///Alexis
        ///Ella
        ///Samantha
        ///Natalie
        ///Grace
        ///Lily
        ///Alyssa
        ///Ashley
        ///Sarah
        ///Taylor
        ///Hannah
        ///Brianna
        ///Hailey
        ///Kaylee
        ///Lillian
        ///Leah
        ///Anna
        ///Allison
        ///Victoria
        ///Avery
        ///Gabriella
        ///Nevaeh
        ///Kayla
        ///Sofia
        ///Brooklyn
        ///Riley
        ///Evelyn
        ///Savannah
        ///Aubrey
        ///Alexa
        ///Peyton
        ///Makayla
        ///Layla
        ///Lauren
        ///Zoe
        ///Sydney
        ///Audrey
        ///Julia
        ///Jasmine
        ///Arianna
        ///Claire
        ///Brooke
        ///Amelia
        ///Morgan
        ///Destiny
        ///Bella
        ///Madelyn
        ///Katherine
        ///Kylie
        ///Maya
        ///Aaliyah
        ///Madeline
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Girl_Names {
            get {
                return ResourceManager.GetString("Girl_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMITH
        ///JOHNSON
        ///WILLIAMS
        ///JONES
        ///BROWN
        ///DAVIS
        ///MILLER
        ///WILSON
        ///MOORE
        ///TAYLOR
        ///ANDERSON
        ///THOMAS
        ///JACKSON
        ///WHITE
        ///HARRIS
        ///MARTIN
        ///THOMPSON
        ///GARCIA
        ///MARTINEZ
        ///ROBINSON
        ///CLARK
        ///RODRIGUEZ
        ///LEWIS
        ///LEE
        ///WALKER
        ///HALL
        ///ALLEN
        ///YOUNG
        ///HERNANDEZ
        ///KING
        ///WRIGHT
        ///LOPEZ
        ///HILL
        ///SCOTT
        ///GREEN
        ///ADAMS
        ///BAKER
        ///GONZALEZ
        ///NELSON
        ///CARTER
        ///MITCHELL
        ///PEREZ
        ///ROBERTS
        ///TURNER
        ///PHILLIPS
        ///CAMPBELL
        ///PARKER
        ///EVANS
        ///EDWARDS
        ///COLLINS
        ///STEWART
        ///SANCHEZ
        ///MORRIS
        ///ROGERS
        ///REED
        ///COOK
        ///MORGAN
        ///BELL
        ///MURPHY
        ///BAILEY
        ///RIVERA
        ///COOPER
        ///RICHARDSON
        ///COX
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Last_Names {
            get {
                return ResourceManager.GetString("Last_Names", resourceCulture);
            }
        }
    }
}
